"""add due_date, fine_amount and status to loan model

Revision ID: 4fa32c1c78c9
Revises: edd43fc12477
Create Date: 2025-12-05 04:46:28.083286

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4fa32c1c78c9'
down_revision: Union[str, Sequence[str], None] = 'edd43fc12477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('due_date', sa.Date(), nullable=False))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(), nullable=True))
    op.add_column('loans', sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus', native_enum=False), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('loans', 'status')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_date')
    # ### end Alembic commands ###
