"""add stock, description, language and publisher to book

Revision ID: edd43fc12477
Revises: 4aa1e2b806ad
Create Date: 2025-12-05 04:11:48.066328

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'edd43fc12477'
down_revision: Union[str, Sequence[str], None] = '4aa1e2b806ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(), nullable=False))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'language')
    op.drop_column('books', 'description')
    op.drop_column('books', 'stock')
    # ### end Alembic commands ###
